services:
  initializer:
    image: alpine
    container_name: initializer
    restart: "no"
    entrypoint: |
      /bin/sh -c "chown 8983:8983 /solr"
    volumes:
      - ./data/solr:/solr

  solr_client:
    depends_on:
      - initializer
    image: solr:8.6.2
    container_name: solr_client
    ports:
      - "8983:8983"
    volumes:
      - ./data/solr:/var/solr/data
